### ISSUE TITLE
Script tag is missing key prop

### ISSUE THREAD

**Issue by christerwpersson** [oprearocks/gatsby-plugin-drip#1]
The build process outputs this warning when this plugin is included:

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in DripCode
```

Solution: Add a key to the script tag generated by `drip-code.js`, e.g:

```
<script
    key="gatsby-plugin-drip-widget"
    type="text/javascript"
    dangerouslySetInnerHTML={createScriptMarkup(account)}
  />
```

**Comment by oprearocks** [comment]
Oh! I guess me disabling GitHub notifications is not such a good idea! Sorry for the delayed response. Can you create a pull request with your update, @christerwpersson ?
